### ISSUE TITLE
Error in storage player

### ISSUE THREAD

**Issue by Saschanski** [morrolinux/mpradio-py#38]
Upon mpradio start:

mpradio main PID is: 859
broadcasting on FM 88.0
storage_player playing: /pirateradio/sounds/bt-connect.wav
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/mpradio/src/storage_player.py", line 86, in __run
    self.play(song)     # blocking
  File "/home/pi/mpradio/src/storage_player.py", line 134, in play
    time_unit = input_container.size/int(input_container.duration/1000000)
ZeroDivisionError: division by zero

using this as workaround:

        try:		
            time_unit = input_container.size/int(input_container.duration/1000000)
        except ZeroDivisionError:
            time_unit = 0

**Comment by morrolinux** [comment]
Oh right! I haven't thoguht about that!
Thanks
